### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by dmetivie** [rotskoff/neuron-birth-death#1]
Hello,
First, thanks for the code! 
In the `gaussian_example.ipynb` I noticed small issues:
- In the various `run_traj_scheme` functions 
`kill_inds = torch.randint(n, (delta_n,), dtype=torch.int).numpy() ` should be replaced by 
`kill_inds = torch.tensor(random.sample(range(n),delta_n), dtype=torch.int).numpy()`
(there is maybe a more elegant tensor friendly way to do that thought).
The problem with the current function `torch.randint` is that it can draw several times the same integer i.e. killing the same particle twice or more which leads to have too much particles at the end of a loop.
For the cloning phase it is ok to clone several time the same particles.

- Another very small issue is at the moment of testing if `acUi` is smaller or larger than some random number I believe that the random number should be drawn only once so that 
```
            acUi = alpha * cU[i,0]
            r = np.random.rand()
            if acUi < 0:
                if r < -acUi:
                    kill_inds.append(i)
      
            elif r < acUi:
                ys = torch.cat((ys,ys[i,:].reshape(1,1)))
                cs = torch.cat((cs,cs[i,:].reshape(1,1)))
                n_cloned+=1
```

- Last comment is a question, I don't understand when 
`cU = cs*(F(ys)-torch.mm(K(ys,ys.t()),cs)/n)` (![$V(\theta_i)$](https://render.githubusercontent.com/render/math?math=%24V(%5Ctheta_i)%24) in your paper) is computed when is ![$\bar{V}$](https://render.githubusercontent.com/render/math?math=%24%5Cbar%7BV%7D%24) subtracted to it? 
In Algo 1 of your paper the quantity computed is ![$V(\theta_i)-\bar{V}$](https://render.githubusercontent.com/render/math?math=%24V(%5Ctheta_i)-%5Cbar%7BV%7D%24).

Thanks

**Comment by rotskoff** [comment]
Hi, 

Thanks so much for the comments! I agree with your observation that randint could be problematic; I've changed the scheme so that it uses `torch.randperm` instead. Note that currently the only issue that might arise is that the number of killed particles is too small because the `kill` function uses `set` which makes the list of indices unique. 

On the second point, I have made the change you suggest, though I am not sure I see the statistical difference: the two events are mutually exclusive so generating a single random number for both events does not seem to be distinct. 

Regarding the last term, you can view this contribution as "population control". If we were to not clone a random selection of particles after particle death, there would be a $\alpha V$ term in the PDE, but because we replace the particles we have killed the scheme corresponds to $\alpha (V-\bar V)$.
